### ISSUE TITLE
Section1/sorting_numbers.c won't wait

### ISSUE THREAD

**Issue by Microsheep** [u1240976/NCTU_OS_2015_HW3#2]
In line 52 of Section1/sorting_numbers.c
I think the getchar() is meant to stop the program from exiting immediately,
but it will eat the "\n" of the user entering the numbers to sort.
adding another getchar() will solve the issue.

**Comment by cwshu** [comment]
hi @Microsheep, thanks for you help.
I have fixed the bug and push it to the master.
